In [1]:
import pandas as pd

facturas = pd.read_csv('facturas.csv')

items = pd.read_csv('items.csv',sep=',', encoding='utf-8')

proveedor = pd.read_csv('facturas_proveedor.csv')

In [2]:
import datetime

current_date = datetime.date.today()

# Calculate the date of yesterday


anterior1 = current_date - datetime.timedelta(days=90)

anterior2 = current_date - datetime.timedelta(days=30)

anterior3 = current_date - datetime.timedelta(days=7)

In [3]:



facturas_90 = facturas[facturas['fecha'] > str(anterior1)]

facturas_30 = facturas[facturas['fecha'] > str(anterior2)]

facturas_7= facturas[facturas['fecha'] > str(anterior3)]

In [4]:
proveedor2 = proveedor[['nombre', 'precio','fecha', 'proveedor']].groupby(['nombre']).agg(fecha = ('fecha','max')).reset_index()

In [5]:
proveedor3 = pd.merge(proveedor,proveedor2, on = ['nombre','fecha'], how = 'right')

In [6]:

proveedor3

,Unnamed: 0.1,Unnamed: 0,id,fecha,nombre,cantidad,precio,total,totalFact,proveedor
0,791.0,0.0,1422,2023-01-28,MINIMOUSE USB LED 706B,8,6100,48800.0,5448164,JALTECH S.A.S
1,2052.0,0.0,1899,2023-06-13,"""T"" COAXIAL",6,900,5400.0,526151,ALBERTO ABS
2,NaN,NaN,3168,2024-10-10,54588 S29D SOUND OUTDOOR 30W (BLACK) - Potente...,2,183781,367562.0,804530,LASUS COLOMBIA
3,NaN,NaN,2021,2024-10-09,ADAPTADOR 12V 1A,6,3250,19500.0,478700,ANDRES
4,NaN,NaN,2578,2024-10-09,ADAPTADOR 12V 2.5A,6,6700,40200.0,478700,ANDRES
...,...,...,...,...,...,...,...,...,...,...
4569,NaN,NaN,2677,2024-09-17,XIAOMI SMART BAND 8 ACTIVE,3,94515,283545.0,660881,LASUS COLOMBIA
4570,NaN,NaN,2677,2024-10-12,XIAOMI SMART BAND 8 ACTIVE NEGROS,4,93000,372000.0,499500,@PC MAYORISTA S.A.S.
4571,NaN,NaN,3170,2024-09-17,XIAOMI SMART BAND 8 ACTIVE-RASTREADFOR DE ACTI...,1,94515,94515.0,660881,LASUS COLOMBIA
4572,NaN,NaN,3169,2024-09-17,Xiaomi Smart Band 9 - Glacier Silver,1,160433,160433.0,433891,LASUS COLOMBIA
4573,1100.0,0.0,1515,2023-03-03,cartucho hp 950 original,1,115000,115000.0,164000,YONATHAN MAURICIO PRADA BLANCO

In [7]:
fac = facturas_90[["nombre","cantidad","fecha"]].groupby("nombre").agg(fecha_ult_90=("fecha","max"),cantidad_ult_90=("cantidad","sum"))

fac1 = facturas_30[["nombre","cantidad","fecha"]].groupby("nombre").agg(cantidad_ult_30=("cantidad","sum"))

fac2 = facturas_7[["nombre","cantidad","fecha"]].groupby("nombre").agg(cantidad_ult_7=("cantidad","sum"))

In [8]:
fac

,fecha_ult_90,cantidad_ult_90
nombre,,
"""T"" COAXIAL",2024-09-29,1
54588 S29D SOUND OUTDOOR 30W (BLACK) - Potente Altavoz para Exteriores,2024-10-17,3
ADAPTADOR 12V 1A,2024-10-30,8
ADAPTADOR 12V 2.5A,2024-09-18,1
ADAPTADOR 12V 2A,2024-08-04,2
...,...,...
XIAOMI REDMI BUDS 5- AURICULARES INALAMBRICOS CON CANCELACION ACRIVA DE SONIDO BLANCOS,2024-10-21,1
XIAOMI REDMI BUDS 6 PLAY AURICULARES INALAMBRICOS,2024-10-16,1
XIAOMI REDMI WATCH 5 ACTIVE,2024-10-19,2
XIAOMI SMART BAND 8 ACTIVE NEGROS,2024-10-19,4
XIAOMI SMART BAND 8 ACTIVE-RASTREADFOR DE ACTIVIDAD ROSADO,2024-10-20,1

In [9]:
df= pd.merge(items, fac, on = 'nombre', how = 'inner')

In [10]:
df2= pd.merge(df, fac1, on = 'nombre', how = 'left')
df3= pd.merge(df2, fac2, on = 'nombre', how = 'left')

In [11]:
todo_junto = pd.merge(df3,proveedor3, on = "nombre", how = "left")

In [12]:
todo_junto.head()

,nombre,cantidad_x,familia,fecha-inicial,proveedor_x,fecha_ult_compra,promedio,precio_ult_compra,fecha_ult_90,cantidad_ult_90,...,cantidad_ult_7,Unnamed: 0.1,Unnamed: 0,id,fecha,cantidad,precio,total,totalFact,proveedor_y
0,MULTITOMA 6 PUERTOS GLOBY,6.0,ENERGIA,2022-11-07,ANDRES,2024-09-19,7390,6721,2024-10-01,2,...,NaN,NaN,NaN,16,2024-09-19,4,7150,26884.0,487766,ANDRES
1,CABLE DE RED 10 MTS,1.0,CABLES,2022-11-07,JALTECH,2024-08-22,4396,3960,2024-10-18,3,...,NaN,NaN,NaN,57,2024-08-22,5,4400,19800.0,1942110,JALTECH
2,CABLE DE RED 10 MTS,1.0,CABLES,2022-11-07,JALTECH,2024-08-22,4396,3960,2024-10-18,3,...,NaN,NaN,NaN,57,2024-08-22,5,4400,19800.0,1942110,JALTECH
3,DIADEMA BLUETOOTH TIPO APPLE P9,2.0,SONIDO,2022-11-07,NIA MEDELLIN,2024-08-01,27000,27000,2024-08-30,1,...,NaN,6118.0,0.0,68,2024-08-01,2,27000,54000.0,910000,NIA MEDELLIN
4,DIADEMA BLUETOOTH TIPO APPLE P9,2.0,SONIDO,2022-11-07,NIA MEDELLIN,2024-08-01,27000,27000,2024-08-30,1,...,NaN,0.0,NaN,68,2024-08-01,2,27000,54000.0,910000,NIA MEDELLIN

In [13]:
todo_junto1 = todo_junto[['nombre','cantidad_x','proveedor_y','fecha','cantidad','precio','fecha_ult_90','cantidad_ult_90','cantidad_ult_30','cantidad_ult_7']]

In [14]:
todo_junto2= todo_junto1.rename(columns={'cantidad_x': 'disponible','cantidad':'ultimo_pedido','proveedor_y':'proveedor','precio':'precio_de_compra','fecha_ult_90':'ultima_venta'})

In [15]:
todo_junto2 = todo_junto2.fillna(0)

def para_pedir(row):
    if row['cantidad_ult_30'] > row['disponible']:
        return (row['cantidad_ult_30'] + row['disponible'])
    else:
        return 0

In [16]:

todo_junto2['pedir'] = todo_junto2.apply(para_pedir, axis = 1)

In [17]:
todo_junto2

,nombre,disponible,proveedor,fecha,ultimo_pedido,precio_de_compra,ultima_venta,cantidad_ult_90,cantidad_ult_30,cantidad_ult_7,pedir
0,MULTITOMA 6 PUERTOS GLOBY,6.0,ANDRES,2024-09-19,4,7150,2024-10-01,2,1.0,0.0,0.0
1,CABLE DE RED 10 MTS,1.0,JALTECH,2024-08-22,5,4400,2024-10-18,3,1.0,0.0,0.0
2,CABLE DE RED 10 MTS,1.0,JALTECH,2024-08-22,5,4400,2024-10-18,3,1.0,0.0,0.0
3,DIADEMA BLUETOOTH TIPO APPLE P9,2.0,NIA MEDELLIN,2024-08-01,2,27000,2024-08-30,1,0.0,0.0,0.0
4,DIADEMA BLUETOOTH TIPO APPLE P9,2.0,NIA MEDELLIN,2024-08-01,2,27000,2024-08-30,1,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
1876,MOUSE INALAMBRICO RECARGABLE BLUETOOTH JALTECH...,1.0,JALTECH,2024-10-21,2,29900,2024-10-29,1,1.0,1.0,0.0
1877,IPHONE 15 128 GB NEGRO,0.0,FOTO Y VIDEO,2024-10-26,1,2840000,2024-10-26,1,1.0,1.0,1.0
1878,PORTATIL LENOVO CORE I5 6TH 8GB +250GB SSD,0.0,VARIOS,2024-10-26,1,300000,2024-10-26,1,1.0,1.0,1.0
1879,TORRE JANUS BLANCA RYZEN 5 4600G + 8GB 8 512 SSD,0.0,JANUS MEDELLIN,2024-10-30,1,1000000,2024-10-28,1,1.0,1.0,1.0
1880,REDMI NOTE 13 PRO 4G 256/8 GB NEGRO,0.0,FOTO Y VIDEO,2024-10-29,1,770000,2024-10-29,1,1.0,1.0,1.0

In [18]:
todo_junto2.to_csv("para_pedidos.csv")

In [19]:
import ezsheets

s = ezsheets.Spreadsheet('https://docs.google.com/spreadsheets/d/1Sdmq9fdJEaH_CBPNp4rYL6auAk2RZjYLKLIrAWdgnX0/edit#gid=0')
sh = s.sheets[0]

import csv

with open('para_pedidos.csv', newline='', encoding='utf-8') as csvfile:
    reader = csv.reader(csvfile)
    data = list(reader)

sh.updateRows(data)